# Generated by Django 5.1.2 on 2024-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebozarapp', '0007_remove_otp_email_otp_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='user',
        ),
        migrations.AddField(
            model_name='otp',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='json_data',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
