# Generated by Django 5.1.2 on 2024-10-24 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebozarapp', '0012_profile_bio_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
