# Generated by Django 5.1.2 on 2024-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebozarapp', '0015_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=True),
        ),
    ]
